/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "./RTC/bsp_rtc.h"



unsigned short int  listwheelindex[6];   //LISTWHEEL选中的项目号
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_LISTWHEEL_0    (GUI_ID_USER + 0x01)
#define ID_LISTWHEEL_1    (GUI_ID_USER + 0x02)
#define ID_LISTWHEEL_2    (GUI_ID_USER + 0x03)
#define ID_LISTWHEEL_3    (GUI_ID_USER + 0x04)
#define ID_LISTWHEEL_4    (GUI_ID_USER + 0x05)
#define ID_LISTWHEEL_5    (GUI_ID_USER + 0x06)
#define ID_BUTTON_0       (GUI_ID_USER + 0x07)
#define ID_TEXT_0         (GUI_ID_USER + 0x08)
#define ID_TEXT_1         (GUI_ID_USER + 0x09)
#define ID_TEXT_2         (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect,  "Calendar",   ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 50, 135, 70, 160, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_1, 100, 135, 70, 160, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_2, 150, 135, 70, 160, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_3, 200, 135, 70, 160, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_4, 250, 135, 70, 160, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_5, 300, 135, 70, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BUTTON",    ID_BUTTON_0, 700, 300, 32, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "TEXT",      ID_TEXT_0,  450, 150, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "TEXT",      ID_TEXT_1,  550, 150, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "TEXT",      ID_TEXT_2,  650, 150, 50, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code

*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
DateStruct datedemo={"2000","02","01","00","00","00"};    //日期,默认初始化为1990年1月1日

//年
const char *_apYear[]= 
{
    "2000", "2001", "2002", "2003", "2004", "2005", "2006", 
    "2007", "2008", "2009", "2010", "2011", "2012", "2013", 
    "2014", "2015", "2016", "2017", "2018", "2019", "2020", 
    "2021", "2022", "2023", "2024", "2025", "2026", "2027", 
    "2028", "2029", "2030", "2031", "2032", "2033","2034",
};

//月
const char *_apMonth[]=
{
    "01", "02", "03", "04", "05", "06", 
    "07", "08", "09", "10", "11", "12",
};

//日
const char *_apDay[]=
{
    "01", "02", "03", "04", "05", "06", 
    "07", "08", "09", "10", "11", "12", 
    "13", "14", "15", "16", "17", "18", 
    "19", "20", "21", "22", "23", "24", 
    "25", "26", "27", "28", "29", "30", "31",
};

//时
const char *Hour[]= 
{
    "00", "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12", "13", 
	"14", "15", "16", "17", "18", "19", "20",
    "21", "22", "23", "24", 
};

//分
const char *Minute[]= 
{
    "00", "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12", "13", 
	"14", "15", "16", "17", "18", "19", "20",
    "21", "22", "23", "24", "25", "26", "27",
	"28", "29", "30", "31", "32", "33", "34",
    "35", "36", "37", "38", "39", "40", "41", 
	"42", "43", "44", "45", "46", "47", "48",
    "49", "50", "51", "52", "53", "54", "55",
	"56", "57", "58", "59", "60", 
};

//秒
const char *Second[]= 
{
    "00", "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12", "13", 
	"14", "15", "16", "17", "18", "19", "20",
    "21", "22", "23", "24", "25", "26", "27",
	"28", "29", "30", "31", "32", "33", "34",
    "35", "36", "37", "38", "39", "40", "41", 
	"42", "43", "44", "45", "46", "47", "48",
    "49", "50", "51", "52", "53", "54", "55",
	"56", "57", "58", "59", "60", 
};

//在LISTWHEEL0上绘制红色指示行
static int ListWheel0_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_BLUE);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}

//在LISTWHEEL1上绘制红色指示行
static int ListWheel1_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_RED);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}

//在LISTWHEEL2上绘制红色指示行
static int ListWheel2_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_RED);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}
//在LISTWHEEL3上绘制红色指示行
static int ListWheel3_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_BLUE);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}

//在LISTWHEEL4上绘制红色指示行
static int ListWheel4_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_RED);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}

//在LISTWHEEL5上绘制红色指示行
static int ListWheel5_OwnerDraw(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo)
{
    switch(pDrawItemInfo->Cmd)
    {
        case WIDGET_ITEM_DRAW_OVERLAY:
            GUI_SetColor(GUI_BLUE);
            GUI_DrawHLine(60,0,80);
            GUI_DrawHLine(90,0,80);
            break;
        default:
            return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  static int LineHeight=30;
  int i;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Calendar'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Calendar");
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0); 
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0); //ok
	WM_SetHasTrans(hItem);
	//WM_SetCallback(hItem, _cbLightButton);
	for(i=0;i<6;i++)
	{
		hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0+i);
        LISTWHEEL_SetFont(hItem,GUI_FONT_16B_ASCII);
        LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTWHEEL_SetSnapPosition(hItem,(150-LineHeight)/2);
		LISTWHEEL_SetLineHeight(hItem,LineHeight);
        LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_RED);

	}
	 //设置Year的LISTWHEEL
	hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
	LISTWHEEL_SetOwnerDraw(hItem, ListWheel0_OwnerDraw);
	for(i=0;i<GUI_COUNTOF(_apYear);i++)
	{
      LISTWHEEL_AddString(hItem,*(_apYear+i));
	}
	 //设置Month的LISTWHEEL
    hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    LISTWHEEL_SetOwnerDraw(hItem,ListWheel1_OwnerDraw);         //绘制红色指示行
    for(i=0;i<GUI_COUNTOF(_apMonth);i++) //添加数据项
    {
        LISTWHEEL_AddString(hItem,*(_apMonth+i));
    }
    
    //设置Day的LISTWHEEL
    hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
    LISTWHEEL_SetOwnerDraw(hItem,ListWheel2_OwnerDraw);         //绘制红色指示行
    for(i=0;i<GUI_COUNTOF(_apDay);i++) //添加数据项
    {
        LISTWHEEL_AddString(hItem,*(_apDay+i));
    }
    //设置Hour的LISTWHEEL
    hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_3);
    LISTWHEEL_SetOwnerDraw(hItem,ListWheel3_OwnerDraw);         //绘制红色指示行
    for(i=0;i<GUI_COUNTOF(Hour);i++) //添加数据项
    {
        LISTWHEEL_AddString(hItem,*(Hour+i));
    }
    //设置Minute的LISTWHEEL
    hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_4);
    LISTWHEEL_SetOwnerDraw(hItem,ListWheel4_OwnerDraw);         //绘制红色指示行
    for(i=0;i<GUI_COUNTOF(Minute);i++) //添加数据项
    {
        LISTWHEEL_AddString(hItem,*(Minute+i));
    }
    //设置Second的LISTWHEEL
    hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_5);
    LISTWHEEL_SetOwnerDraw(hItem,ListWheel5_OwnerDraw);         //绘制红色指示行
    for(i=0;i<GUI_COUNTOF(Second);i++) //添加数据项
    {
        LISTWHEEL_AddString(hItem,*(Second+i));
    }
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END

	//初始化BUTTON
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "ok");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
	TEXT_SetText(hItem, "year");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
//	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
	TEXT_SetText(hItem, "month");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
//	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA);
	TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
	TEXT_SetText(hItem, "day");
    break;
  case WM_PAINT:
	  	GUI_DrawGradientV(0,			   /* 左上角X 位置 */
						  0,			   /* 左上角Y 位置 */
						  800,	   	       /* 右下角X 位置 */
						  480,  	   	   /* 右下角Y 位置 */
						  GUI_WHITE,	   /* 矩形最左侧要绘制的颜色 */
						  GUI_BLUE);  /* 矩形最右侧要绘制的颜色 */

	  GUI_DrawGradientV(35,50,400,400,GUI_RED,GUI_BLUE);
	  GUI_SetColor(GUI_RED);
	  GUI_SetFont(GUI_FONT_16B_ASCII);
	  GUI_DispStringAt(datedemo.year,450,200); //显示年
  	  GUI_DispStringAt(datedemo.month,550,200);//显示月
	  GUI_DispStringAt(datedemo.day,650,200); //显示日
      break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	switch(Id) 
   {
       
        case ID_LISTWHEEL_0: 
            switch(NCode) 
            {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    break;
                case WM_NOTIFICATION_SEL_CHANGED:
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
                    listwheelindex[0]=LISTWHEEL_GetPos(hItem);      //获取当前所选数据项的索引
                    //注意：LISTWHEEL_GetPos()只是获取到滚轮停下来所选中的那个项目编号，但是此时并没有选中这个
                    //项目，必须调用LISTWHEEL_SetSel()来选中这个项目。
                    LISTWHEEL_SetSel(hItem,listwheelindex[0]);      //设置当前所选数据项，
                    LISTWHEEL_GetItemText(hItem,listwheelindex[0],datedemo.year,5);//获取所选中的项目的文本
                    break;
            }
            break;
        case ID_LISTWHEEL_1: 
            switch(NCode) 
            {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    break;
                case WM_NOTIFICATION_SEL_CHANGED:
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
                    listwheelindex[1]=LISTWHEEL_GetPos(hItem);  //获取当前所选数据项的索引
                    LISTWHEEL_SetSel(hItem,listwheelindex[1]);  //设置当前所选数据项
                    LISTWHEEL_GetItemText(hItem,listwheelindex[1],datedemo.month,20);//获取所选中的项目的文本
                    break;
            }
            break;
        case ID_LISTWHEEL_2: 
            switch(NCode) 
            {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    break;
                case WM_NOTIFICATION_SEL_CHANGED:
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
                    listwheelindex[2]=LISTWHEEL_GetPos(hItem);  //获取当前所选数据项的索引
                    LISTWHEEL_SetSel(hItem,listwheelindex[2]);  //设置当前所选数据项
                    LISTWHEEL_GetItemText(hItem,listwheelindex[2],datedemo.day,5);//获取所选中的项目的文本
                    break;
            }
            break;
		case ID_LISTWHEEL_3: // Notifications sent by 'Listwheel'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				// USER END
			break;
		  case WM_NOTIFICATION_SEL_CHANGED:
			// USER START (Optionally insert code for reacting on notification message)
            hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
            listwheelindex[3]=LISTWHEEL_GetPos(hItem);  //获取当前所选数据项的索引
            LISTWHEEL_SetSel(hItem,listwheelindex[3]);  //设置当前所选数据项
            LISTWHEEL_GetItemText(hItem,listwheelindex[3],datedemo.hour,3);//获取所选中的项目的文本
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
		case ID_LISTWHEEL_4: // Notifications sent by 'Listwheel'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_SEL_CHANGED:
			// USER START (Optionally insert code for reacting on notification message)
            hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
            listwheelindex[4]=LISTWHEEL_GetPos(hItem);  //获取当前所选数据项的索引
            LISTWHEEL_SetSel(hItem,listwheelindex[4]);  //设置当前所选数据项
            LISTWHEEL_GetItemText(hItem,listwheelindex[4],datedemo.minute,3);//获取所选中的项目的文本
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
         case ID_LISTWHEEL_5: // Notifications sent by 'Listwheel'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				// USER END
			break;
		  case WM_NOTIFICATION_SEL_CHANGED:
			// USER START (Optionally insert code for reacting on notification message)
            hItem=WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
            listwheelindex[5]=LISTWHEEL_GetPos(hItem);  //获取当前所选数据项的索引
            LISTWHEEL_SetSel(hItem,listwheelindex[5]);  //设置当前所选数据项
            LISTWHEEL_GetItemText(hItem,listwheelindex[5],datedemo.second,3);//获取所选中的项目的文本
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
	   case ID_BUTTON_0: 
            switch(NCode) 
            {
                case WM_NOTIFICATION_CLICKED:
                     RTC_TimeAndDate_Set();
                    break;
                case WM_NOTIFICATION_RELEASED:
                   
                    WM_InvalidateWindow(pMsg->hWin);     //FRAMEWIN窗口无效
                    break;
            }
            break;
	}
		break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCalendar
*/
WM_HWIN CreateCalendar(void);
WM_HWIN CreateCalendar(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
