/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

// USER END

#include "DIALOG.h"
#include "./led/bsp_led.h"   
#include "xbffontcreate.h"
#include "./mp3Player/mp3Player.h"
#include "FreeRTOS.h"
#include "task.h"

extern GUI_CONST_STORAGE GUI_BITMAP bmfengsan;
extern GUI_CONST_STORAGE GUI_BITMAP bmclock;
extern GUI_CONST_STORAGE GUI_BITMAP bmCamera;
extern GUI_CONST_STORAGE GUI_BITMAP bmphone;
extern GUI_CONST_STORAGE GUI_BITMAP bmlight;
extern GUI_CONST_STORAGE GUI_BITMAP bmdamp;
extern GUI_CONST_STORAGE GUI_BITMAP bmcurtain;
extern GUI_CONST_STORAGE GUI_BITMAP bmdoor;
extern GUI_CONST_STORAGE GUI_BITMAP bmcalendar;
extern GUI_CONST_STORAGE GUI_BITMAP bmmusic;
extern GUI_CONST_STORAGE GUI_BITMAP bmtempature;
extern GUI_CONST_STORAGE GUI_BITMAP bmmessage;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
extern  WM_HWIN CreateTemperature(void);
extern  WM_HWIN CreateCalendar(void);
extern  WM_HWIN CreateAlarmClock(void);
extern  WM_HWIN CreateDamp(void);
extern  WM_HWIN CreateDOOR(void);
extern  WM_HWIN CreateWind(void);
extern  WM_HWIN CreateCurtain(void);
extern  void keypad_demo(void);

#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_2    (GUI_ID_USER + 0x03)
#define ID_BUTTON_3    (GUI_ID_USER + 0x04)
#define ID_BUTTON_4    (GUI_ID_USER + 0x05)
#define ID_BUTTON_5    (GUI_ID_USER + 0x06)
#define ID_BUTTON_6    (GUI_ID_USER + 0x07)
#define ID_BUTTON_7    (GUI_ID_USER + 0x08)
#define ID_BUTTON_8    (GUI_ID_USER + 0x09)
#define ID_BUTTON_9    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12    (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13    (GUI_ID_USER + 0x0E)
#define ID_TEXT_0     (GUI_ID_USER + 0x0F)
#define ID_TEXT_1     (GUI_ID_USER + 0x10)
#define ID_TEXT_2     (GUI_ID_USER + 0x11)
#define ID_TEXT_3     (GUI_ID_USER + 0x12)
#define ID_TEXT_4     (GUI_ID_USER + 0x13)
#define ID_TEXT_5     (GUI_ID_USER + 0x14)
#define ID_TEXT_6     (GUI_ID_USER + 0x15)
#define ID_TEXT_7     (GUI_ID_USER + 0x16)
#define ID_TEXT_8     (GUI_ID_USER + 0x17)
#define ID_TEXT_9     (GUI_ID_USER + 0x18)
#define ID_TEXT_10     (GUI_ID_USER + 0x19)
#define ID_TEXT_11    (GUI_ID_USER + 0x1A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "dorm", ID_FRAMEWIN_0, -1, -5, 800, 480, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 50, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 172, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 414, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 291, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 536, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 658, 70, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 50, 222, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 172, 222, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 291, 222, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 414, 222, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 536, 222, 72, 72, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 658, 222, 72, 72, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 40, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 162, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 404, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 281, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 526, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 648, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 40, 312,  100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 162, 312, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 281, 312, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 388, 312, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 526, 312, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 648, 312, 100, 20, 0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 50, 324, 72, 72, 0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 172, 324, 72, 72, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _cbLightButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmdamp, 0, 0);				
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbFengshanButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmfengsan, 0, 0);				
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbClockButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmclock, 0, 0);				
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbCameraButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmCamera, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbTelephoneButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmphone, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbCurtainButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmcurtain, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbDoorButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmdoor, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}


static void _cbcalendarButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmcalendar, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbmusicButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmmusic, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbtempatureButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmtempature, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbmessageButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{ 
				GUI_DrawBitmap(&bmmessage, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbWifiButton(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;

	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_BLUE);
				GUI_Clear();
			} 
			else 
			{          
				GUI_DrawBitmap(&bmwifi, 0, 0);
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'dorm'
    //
     GUI_SetAlpha(0XFF);
	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0); //灯
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbLightButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3); //风扇
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbFengshanButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1); //时钟
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbClockButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2); //摄像头
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbCameraButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4); //电话
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbTelephoneButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5); //窗帘
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbCurtainButton);
	 
	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6); //门
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbDoorButton);
	 
	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7); //日历
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbcalendarButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8); //音乐
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbmusicButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9); //温湿度
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbtempatureButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10); //短信
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbmessageButton);

	 hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11); //wifi
	 WM_SetHasTrans(hItem);
	 WM_SetCallback(hItem, _cbWifiButton);
	 
	 
	 
    //
    // Initialization of 'Text'
    //
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
    TEXT_SetText(hItem,"light");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "clock");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
	TEXT_SetText(hItem, "camera");


	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "wind");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "phone");


	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
	TEXT_SetText(hItem, "curtain");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
	TEXT_SetText(hItem, "door");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "calendar");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
	TEXT_SetText(hItem, "music");


	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "temperature");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem, GUI_FONT_24_1);
	TEXT_SetText(hItem, "message");


	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,GUI_FONT_24_1);
	TEXT_SetText(hItem, "WIFI");

    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Intelligent  dorm");
    FRAMEWIN_SetTitleHeight(hItem, 40);
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetBarColor(hItem,0,GUI_BLUE);
    FRAMEWIN_SetBarColor(hItem,1,GUI_RED);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
		case WM_PAINT:
		GUI_DrawGradientV(0,			   /* 左上角X 位置 */
						  0,			   /* 左上角Y 位置 */
						  800,	   	       /* 右下角X 位置 */
						  480,  	   	   /* 右下角Y 位置 */
						  GUI_WHITE,	   /* 矩形最左侧要绘制的颜色 */
						  GUI_BLUE);  /* 矩形最右侧要绘制的颜色 */
		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      CreateDamp();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      LED3_OFF;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
         CreateAlarmClock();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
         CreateWind();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      keypad_demo();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      CreateCurtain();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      CreateDOOR();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      CreateCalendar();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        taskENTER_CRITICAL();//进入临界区
        mp3PlayerDemo("0:/mp3/张国荣-玻璃之情.mp3");
		mp3PlayerDemo("0:/mp3/张国荣-全赖有你.mp3");
    	taskEXIT_CRITICAL();//退出临界区      
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      	  CreateTemperature();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createdorm
*/
WM_HWIN Createdorm(void);
WM_HWIN Createdorm(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
